Initial project infrastructure
kpi-web-guild/Pyramid-Miseracle pull request #1
Opened 2017-04-23 11:30 UTC by Miseracle

Add initial project infrastructure - containers, linter, Travis integration and a simple "Hello-world" app.

2017-04-23 15:56 UTC, webknjaz requested changes
* `main` is too common, normally packages are called after the project
* `__init__.py` isn't required at all under Python 3

2017-04-23 15:56 UTC, webknjaz commented on .pre-commit-config.yaml
> +        exclude: /__init__.py
I think you shouldn't ignore this

2017-04-23 15:56 UTC, webknjaz commented on .pre-commit-config.yaml
> +        - --django
YAGNI

2017-04-23 15:56 UTC, webknjaz commented on .pre-commit-config.yaml
> +        exclude: /__init__.py
YAGNI

2017-04-23 15:56 UTC, webknjaz commented on .travis.yml
> +python: 3.5
3.6

2017-04-23 15:56 UTC, webknjaz commented on README.md
> +# My project to learn something about Pyramid etc.
`This is ...`

2017-04-23 15:56 UTC, webknjaz commented on main/app.py
> +    config = Configurator()
Wrap this piece of code into function `main()` and call it here.

2017-04-23 15:56 UTC, webknjaz commented on vagga.yaml
> +    - !Depends .pre-commit-config.yaml
I think, this container doesn't need to depend on this config.

2017-04-23 17:16 UTC, Miseracle commented on README.md
> +# My project to learn something about Pyramid etc.
Mad English skills :D

2017-04-23 17:20 UTC, Miseracle commented
I used "main" as a default name - like "foo", "dummy" etc. Will rename it later, right after specifying this project.

2017-04-23 18:34 UTC, Miseracle commented
Added container for pytest tests.

2017-04-23 20:11 UTC, webknjaz requested changes

2017-04-23 20:11 UTC, webknjaz commented on main/app.py
> +main()
Here's what I meant:
```python
if __name__ == '__main__':
    main()
```

2017-04-23 20:11 UTC, webknjaz commented on main/app.py
> +    if __name__ == '__main__':
this check should be at module level

2017-04-23 20:11 UTC, webknjaz commented on vagga.yaml
> +    run: python3 main/tests.py
python3 -> pytest

2017-04-23 20:13 UTC, webknjaz requested changes

2017-04-23 20:13 UTC, webknjaz commented on main/app.py
> +    if __name__ == '__main__':
this check should be at module level

2017-04-23 20:13 UTC, webknjaz commented on main/app.py
> +main()
Here's what I meant:
```python
if __name__ == '__main__':
    main()
```

2017-04-23 20:13 UTC, webknjaz commented on vagga.yaml
> +    run: python3 main/tests.py
python3 -> pytest

2017-04-23 20:30 UTC, Miseracle commented on main/app.py
> +main()
Oh, got it. Looks like an inversed main() method in other programming languages.

2017-04-23 21:18 UTC, webknjaz approved these changes
Feel free to merge this if you checked that it's working.

2017-04-24 19:24 UTC, merged

2017-04-25 12:57 UTC, webknjaz commented on main/app.py
> +main()
It's not inversed. The point is that every time you import some module it's contents are being evaluated. This check ensures that it's the direct run of the module via either `./module.py`, or `python -m module`, or `python ./module.py`. In such case `__name__` var is populated with `'__main__'` value, but it contains the actual name of the module whenever it's being imported from other places via `import` statement.